openapi: 3.0.1
info:
  title: Auth microservice
  version: 1.0.0

paths: {}

components:
  schemas:
    RoleResponseDto:
      $ref: 'models/role-response.yaml#/RoleResponseDTO'
    UserResponseDto:
      $ref: 'models/user-response.yaml#/UserResponseDTO'
